apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lyr6tijs0-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lyr6tijs0-java-quarkus-gitops